name: dnd_handy_flutter
description: Handy DnD app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 0.2.0+1

environment:
  sdk: ^3.1.3

# To upgrade: `flutter pub upgrade --major-versions`
# To detect new versions: `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.6.15
  shared_preferences: ^2.1.2
  go_router: ^11.0.0
  libadwaita: ^2.0.0
  adwaita: ^1.1.0

  path_provider: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # See `analysis_options.yaml` for linting options.
  flutter_lints: ^2.0.2

  hive_generator: ^2.0.1
  build_runner: ^2.4.2

# More information: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
